src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le titre ne doit pas être vide")
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=100, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="articles")
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull(message="Veuillez saisir un auteur")
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $specificLocationName;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath()
    {
        return 'images/'.$this->getImageFilename();
    }

    public function incrementHeartCount(): self
    {
        $this->heartCount = $this->heartCount + 1;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        $criteria = ArticleRepository::createNonDeletedCriteria();

        return $this->comments->matching($criteria);
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function isPublished()
    {
        return $this->publishedAt != null;
    }

    /**
     * @param ExecutionContextInterface $context
     * @param $payload
     * @Assert\Callback()
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if(stripos($this->getTitle(), 'the borg') !== false) {
            $context->buildViolation('Erreur : the borg')
                    ->atPath('title')
                    ->addViolation();
        }
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getSpecificLocationName(): ?string
    {
        return $this->specificLocationName;
    }

    public function setSpecificLocationName(?string $specificLocationName): self
    {
        if (!$this->location || $this->location === 'interstellar_space') {
            $this->setSpecificLocationName(null);
        }

        $this->specificLocationName = $specificLocationName;

        return $this;
    }
}

src/Controller/ArticleController.php
<?php


namespace App\Controller;


use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use App\Service\MarkdownHelper;
use App\Service\SlackClient;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function homepage(ArticleRepository $repository)
    {
        $articles = $repository->findAllPublishedOrderedByNewest();
        return $this->render('article/homepage.html.twig', ['articles' => $articles]);
    }

    /**
     * @Route("/news/{slug}", name="news")
     */
    public function show(Article $article, SlackClient $slack)
    {
        if($article->getSlug() === 'yo') {
            $slack->sendMessage('Jéjé', 'Bonjour la famille');
        }

        return $this->render('article/show.html.twig', [
            'article' => $article]);
    }

    /**
     * @Route("/news/{slug}/heart", name="article_toggle_heart", methods={"POST"})
     */
    public function toggleArticleHeart(Article $article, LoggerInterface $logger, EntityManagerInterface $em)
    {
        $article->incrementHeartCount();
        $em->flush($article);

        $logger->info('Article is being hearted !');
        return new JsonResponse(['hearts' => $article->getHeartCount()]);
    }
}

templates/article/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} Accueil
{% endblock %}

{% block body %}
    <h1 class="text-center">Accueil</h1>

    <div class="row">
        {% for article in articles %}
        <div class="col-md-4">
            <div class="card">
                <img src="{{ asset(article.imagePath) }}" class="card-img-top" alt="...">
                <div class="tags-home">
                    {% for tag in article.tags %}
                        <span class="badge badge-info">{{ tag.name }}</span>
                    {% endfor %}
                </div>
                <hr>
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <p>Publié par {{ article.author }} - {{ article.publishedAt ? article.publishedAt|ago }}</p>
                    <p>{{ article.nonDeletedComments|length }} commentaires</p>
                    <a href="{{ path('news', {'slug': article.slug }) }}" class="btn btn-primary">Lire l'article</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ parent() }} {{ article.title }} {% endblock %}
{% block body %}
    <article>
        <div class="header-article">
            <img class="mx-auto d-block" width="300" src="{{ asset(article.imagePath) }}" />
            <hr>
            <h1>{{ article.title }}</h1>
            <div class="tags">
                {% for tag in article.tags %}
                    <span class="badge badge-info">{{ tag.name }}</span>
                {% endfor %}
            </div>
            <span class="info"><img class="rounded-circle" width="35" height="35" src="https://randomuser.me/api/portraits/women/48.jpg" /> {{ article.author }} - {{ article.publishedAt ? article.publishedAt|ago : 'non publié' }} - {{ article.comments|length }} commentaires | <span class="like-counter">{{ article.heartCount }}</span> <a href="{{ path('article_toggle_heart', {'slug': article.slug}) }}" class="like-article"><i class="far fa-heart" style="color: red;"></i></a></span>
        </div>
        <div>
            {{ article.content|cached_markdown }}
        </div>
    </article>

    <section id="comments">
        <h2>{{ article.nonDeletedComments|length }} commentaires </h2>
        <hr>
        {% for comment in article.nonDeletedComments %}
        <div class="card">
            <div class="card-header">
                {% if comment.isDeleted %}
                    <span class="fa fa-close"></span> supprimé
                {% endif %}
                {{ comment.authorName }} <br />
                {{ comment.createdAt|ago }}
            </div>
            <div class="card-body">
                <p class="card-text">{{ comment.content }}</p>
            </div>
        </div>
        {% endfor %}
    </section>



{% endblock %}

{% block javascripts %}
    {{ parent() }}
   {{ encore_entry_script_tags('news_show') }}
{% endblock %}